import { NextRequest, NextResponse } from "next/server";
import PDFDocument from "pdfkit";import { prisma } from "@/lib/prisma";
const labels:Record<string,string>={kompetensiAwal:"Kompetensi Awal",profilPelajarPancasila:"Profil Pelajar Pancasila",saranaPrasarana:"Sarana dan Prasarana",modelPembelajaran:"Model Pembelajaran",pemahamanBermakna:"Pemahaman Bermakna",pertanyaanPemantik:"Pertanyaan Pemantik",kegiatanPendahuluan:"Kegiatan Pendahuluan",kegiatanInti:"Kegiatan Inti",kegiatanPenutup:"Kegiatan Penutup",asesmen:"Asesmen",remedialPengayaan:"Remedial dan Pengayaan",refleksiGuru:"Refleksi Guru",catatanTambahan:"Catatan Tambahan",cp:"Capaian Pembelajaran (CP)",tp:"Tujuan Pembelajaran (TP)",atp:"Alur Tujuan Pembelajaran (ATP)",materi:"Materi Pembelajaran",fase:"Fase",semester:"Semester",alokasiWaktu:"Alokasi Waktu",namaGuru:"Nama Guru",nipGuru:"NIP Guru",tempatTanggal:"Tempat, Tanggal"};
function label(k:string){return labels[k]||k.replace(/([A-Z])/g," $1").replace(/^./,s=>s.toUpperCase())}function value(v:unknown){return v==null?"":String(v).trim()}
export async function GET(req:NextRequest,{params}:{params:Promise<{id:string}>}){try{const {id}=await params;const device=await prisma.teachingDevice.findUnique({where:{id},include:{school:true}});if(!device)return NextResponse.json({error:"Perangkat tidak ditemukan."},{status:404});const content=(device.content||{}) as Record<string,unknown>;const school=device.school;const doc=new PDFDocument({size:"A4",margin:48});const chunks:Buffer[]=[];doc.on("data",b=>chunks.push(b));const done=new Promise<Buffer>((resolve,reject)=>{doc.on("end",()=>resolve(Buffer.concat(chunks)));doc.on("error",reject)});
doc.fontSize(15).font("Helvetica-Bold").text(school?.name||value(content.namaSekolah)||"Nama Sekolah",{align:"center"});if(school?.address||content.alamatSekolah)doc.fontSize(9).font("Helvetica").text(school?.address||value(content.alamatSekolah),{align:"center"});if(school?.npsn)doc.fontSize(8).text("NPSN: "+school.npsn,{align:"center"});doc.moveDown(.4).moveTo(48,doc.y).lineTo(547,doc.y).stroke().moveDown(1);doc.fontSize(18).font("Helvetica-Bold").text("MODUL AJAR",{align:"center"});doc.fontSize(13).text(device.title,{align:"center"}).moveDown(1);
const meta=[["Nama Sekolah",school?.name||value(content.namaSekolah)],["Nama Guru",value(content.namaGuru)||"-"],["Mata Pelajaran",device.subjectName||"-"],["Fase / Kelas",`${value(content.fase)||"-"} / ${device.className||"-"}`],["Semester",value(content.semester)||"-"],["Tahun Ajaran",device.academicYear||"-"],["Alokasi Waktu",value(content.alokasiWaktu)||"-"]];for(const [a,b] of meta){doc.fontSize(9).font("Helvetica-Bold").text(a+": ",{continued:true});doc.font("Helvetica").text(b||"-")}doc.moveDown(1);
const preferred=["cp","tp","atp","materi","kompetensiAwal","profilPelajarPancasila","saranaPrasarana","modelPembelajaran","pemahamanBermakna","pertanyaanPemantik","kegiatanPendahuluan","kegiatanInti","kegiatanPenutup","asesmen","remedialPengayaan","refleksiGuru","catatanTambahan"];for(const key of preferred){const v=value(content[key]);if(!v)continue;doc.fontSize(11).font("Helvetica-Bold").text(label(key));doc.moveDown(.2).fontSize(9.5).font("Helvetica").text(v,{lineGap:3});doc.moveDown(.7)}
doc.moveDown(1.5).text(value(content.tempatTanggal)||"__________________, __________________",{align:"right"}).text("Mengetahui,",{align:"right"}).text(school?.name||"Nama Sekolah",{align:"right"}).text("Kepala Sekolah",{align:"right"}).moveDown(2.5).font("Helvetica-Bold").text(school?.principalName||"________________________",{align:"right"});if(school?.principalNip)doc.font("Helvetica").text("NIP. "+school.principalNip,{align:"right"});if(value(content.namaGuru)){doc.moveDown(1).font("Helvetica").text("Guru Mata Pelajaran").moveDown(2.5).font("Helvetica-Bold").text(value(content.namaGuru));if(value(content.nipGuru))doc.font("Helvetica").text("NIP. "+value(content.nipGuru))}doc.end();const buffer=await done;const filename=device.title.replace(/[^a-zA-Z0-9_-]+/g,"-")+".pdf";return new NextResponse(buffer,{headers:{"Content-Type":"application/pdf","Content-Disposition":`attachment; filename="\${filename}"`}})}catch(error){console.error(error);return NextResponse.json({error:"Gagal membuat PDF."},{status:500})}}
