"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,Eye,Save,FileText} from "lucide-react";
import {useParams} from "next/navigation";
import "./page.css";
export default function DeviceEditor(){
 const p=useParams();const [data,setData]=useState<any>(null);const [loading,setLoading]=useState(true);const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 useEffect(()=>{fetch("/api/perangkat/"+p.id).then(r=>r.json()).then(setData).finally(()=>setLoading(false))},[p.id]);
 const update=(k:string,v:any)=>setData((d:any)=>({...d,[k]:v}));
 const updateContent=(k:string,v:any)=>setData((d:any)=>({...d,content:{...(d.content||{}),[k]:v}}));
 async function save(){setSaving(true);setMessage("");const r=await fetch("/api/perangkat/"+p.id,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:data.title,subjectName:data.subjectName,className:data.className,academicYear:data.academicYear,content:data.content})});setMessage(r.ok?"Perubahan tersimpan.":"Gagal menyimpan.");setSaving(false)}
 if(loading)return <main className="deviceShell"><p>Memuat...</p></main>;
 if(!data?.id)return <main className="deviceShell"><p>Perangkat tidak ditemukan.</p></main>;
 const entries=Object.entries(data.content||{}).filter(([k,v])=>k!=="catatan"&&String(v||"").trim());
 return <main className="deviceShell"><header className="deviceTop"><div><Link href="/perangkat-ajar/saya" className="back"><ArrowLeft size={16}/> Perangkat Ajar Saya</Link><p className="eyebrow">EDITOR PERANGKAT</p><h1>{data.title}</h1><p className="muted">{data.type} • {data.subjectName||"Belum diisi"} • Kelas {data.className||"-"}</p></div><div className="deviceActions"><button onClick={()=>document.getElementById("preview")?.scrollIntoView({behavior:"smooth"})}><Eye size={16}/> Preview</button><a className="exportBtn" href={"/api/perangkat/"+p.id+"/docx"}><FileText size={16}/> DOCX</a><a className="exportBtn pdf" href={"/api/perangkat/"+p.id+"/pdf"}><FileText size={16}/> PDF</a><button className="primary" disabled={saving} onClick={save}><Save size={16}/>{saving?"Menyimpan":"Simpan"}</button></div></header>
 <section className="editCard"><h2>Rantai Kurikulum</h2><div className="previewMeta">Kurikulum → Fase → Mata Pelajaran → CP → TP → ATP → Materi</div><div className="chainBox">{data.curriculumId&&<span>Kurikulum ✓</span>}{data.phaseId&&<span>Fase ✓</span>}{data.outcomeId&&<span>CP ✓</span>}{data.objectiveId&&<span>TP ✓</span>}{data.sequenceId&&<span>ATP ✓</span>}{data.materialId&&<span>Materi ✓</span>}{!data.curriculumId&&<span>Belum terhubung ke kurikulum</span>}</div></section><section className="editCard"><h2>Informasi Utama</h2><div className="editGrid"><label>Judul<input value={data.title||""} onChange={e=>update("title",e.target.value)}/></label><label>Mata Pelajaran<input value={data.subjectName||""} onChange={e=>update("subjectName",e.target.value)}/></label><label>Kelas<input value={data.className||""} onChange={e=>update("className",e.target.value)}/></label><label>Tahun Ajaran<input value={data.academicYear||""} onChange={e=>update("academicYear",e.target.value)}/></label></div></section>
 <section className="editCard"><h2>Isi Perangkat</h2><div className="contentGrid">{entries.map(([key,value])=><label key={key}>{key.replace(/([A-Z])/g," $1")}<textarea value={String(value)} onChange={e=>updateContent(key,e.target.value)}/></label>)}</div><label>Catatan<textarea value={data.content?.catatan||""} onChange={e=>updateContent("catatan",e.target.value)}/></label>{message&&<p className="saved">{message}</p>}</section>
 <section className="previewCard" id="preview"><div className="previewTitle"><FileText size={18}/><div><span>PREVIEW</span><h2>{data.title}</h2></div></div><div className="previewMeta">{data.subjectName&&<b>{data.subjectName}</b>} {data.className&&<>• Kelas {data.className}</>} {data.academicYear&&<>• {data.academicYear}</>}</div>{entries.map(([key,value])=><article key={key}><h3>{key.replace(/([A-Z])/g," $1")}</h3><p>{String(value)}</p></article>)}</section></main>
}