import "./page.css";
"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {ArrowLeft,BookOpen,FileText,Save,ChevronRight,Target,Route,Layers} from "lucide-react";
const types=[["MODUL_AJAR","Modul Ajar"],["LKPD","LKPD"],["BAHAN_AJAR","Bahan Ajar"],["ASESMEN","Asesmen"],["KISI_KISI","Kisi-Kisi"],["PROGRAM_SEMESTER","Program Semester"],["PROGRAM_TAHUNAN","Program Tahunan"]];
const ref=(kind:string,id?:string)=>`/api/perangkat/referensi?kind=${kind}${id?"&id="+encodeURIComponent(id):""}`;
const moduleFields=[["namaGuru","Nama Guru","Nama guru penyusun modul."],["nipGuru","NIP Guru","Opsional, jika digunakan pada dokumen resmi."],["fase","Fase","Contoh: D."],["semester","Semester","Contoh: Ganjil."],["alokasiWaktu","Alokasi Waktu","Contoh: 2 JP (80 menit)."],["tempatTanggal","Tempat, Tanggal","Tempat dan tanggal penandatanganan."],["cp","Capaian Pembelajaran (CP)","Ringkasan CP yang dipilih dari Master Kurikulum."],["tp","Tujuan Pembelajaran (TP)","Tujuan pembelajaran yang digunakan."],["atp","Alur Tujuan Pembelajaran (ATP)","Alur tujuan pembelajaran."],["materi","Materi Pembelajaran","Materi pokok yang dipelajari."],["kompetensiAwal","Kompetensi Awal","Kemampuan/prasyarat yang perlu dimiliki peserta didik."],["profilPelajarPancasila","Profil Pelajar Pancasila","Dimensi/profil yang dikembangkan."],["saranaPrasarana","Sarana dan Prasarana","Media, alat, dan sumber belajar."],["modelPembelajaran","Model Pembelajaran","Contoh: PBL, PjBL, Discovery Learning."],["pemahamanBermakna","Pemahaman Bermakna","Pemahaman utama yang diharapkan terbentuk."],["pertanyaanPemantik","Pertanyaan Pemantik","Pertanyaan awal untuk mengarahkan pembelajaran."],["kegiatanPendahuluan","Kegiatan Pendahuluan","Kegiatan pembuka dan apersepsi."],["kegiatanInti","Kegiatan Inti","Langkah pembelajaran utama."],["kegiatanPenutup","Kegiatan Penutup","Refleksi, simpulan, dan tindak lanjut."],["asesmen","Asesmen","Asesmen diagnostik, formatif, dan sumatif."],["remedialPengayaan","Remedial dan Pengayaan","Tindak lanjut bagi peserta didik."],["refleksiGuru","Refleksi Guru","Catatan refleksi setelah pembelajaran."]];
export default function PerangkatPage(){
 const [type,setType]=useState("MODUL_AJAR");const [refs,setRefs]=useState<any>({});const [saving,setSaving]=useState(false);const [message,setMessage]=useState("");
 const [form,setForm]=useState<any>({ownerUserId:"demo-teacher",title:"",subjectName:"",className:"",academicYear:"2026/2027",content:{}});
 useEffect(()=>{fetch(ref("curricula")).then(r=>r.ok?r.json():[]).then(v=>setRefs((x:any)=>({...x,curricula:v}))).catch(()=>{})},[]);
 useEffect(()=>{if(!form.curriculumId){setRefs((x:any)=>({...x,phases:[]}));return} fetch(ref("phases")+"&curriculumId="+encodeURIComponent(form.curriculumId)).then(r=>r.ok?r.json():[]).then(v=>setRefs((x:any)=>({...x,phases:v}))).catch(()=>{})},[form.curriculumId]);
 useEffect(()=>{if(!form.phaseId||!form.subjectId){setRefs((x:any)=>({...x,outcomes:[]}));return} fetch(ref("outcomes")+"&curriculumId="+encodeURIComponent(form.curriculumId)+"&phaseId="+encodeURIComponent(form.phaseId)+"&subjectId="+encodeURIComponent(form.subjectId)).then(r=>r.ok?r.json():[]).then(v=>setRefs((x:any)=>({...x,outcomes:v}))).catch(()=>{})},[form.curriculumId,form.phaseId,form.subjectId]);
 useEffect(()=>{if(!form.outcomeId){setRefs((x:any)=>({...x,objectives:[]}));return} fetch(ref("objectives",form.outcomeId)+"&curriculumId="+encodeURIComponent(form.curriculumId)).then(r=>r.ok?r.json():[]).then(v=>setRefs((x:any)=>({...x,objectives:v}))).catch(()=>{})},[form.outcomeId]);
 useEffect(()=>{if(!form.objectiveId){setRefs((x:any)=>({...x,sequences:[]}));return} fetch(ref("sequences",form.objectiveId)+"&curriculumId="+encodeURIComponent(form.curriculumId)).then(r=>r.ok?r.json():[]).then(v=>setRefs((x:any)=>({...x,sequences:v}))).catch(()=>{})},[form.objectiveId]);
 useEffect(()=>{if(!form.sequenceId){setRefs((x:any)=>({...x,materials:[]}));return} fetch(ref("materials",form.sequenceId)+"&curriculumId="+encodeURIComponent(form.curriculumId)).then(r=>r.ok?r.json():[]).then(v=>setRefs((x:any)=>({...x,materials:v}))).catch(()=>{})},[form.sequenceId]);
 useEffect(()=>{if(!form.curriculumId){setRefs((x:any)=>({...x,subjects:[]}));return}fetch(ref("subjects")+"&curriculumId="+encodeURIComponent(form.curriculumId)).then(r=>r.ok?r.json():[]).then(v=>setRefs((x:any)=>({...x,subjects:v}))).catch(()=>{})},[form.curriculumId]);

 const filteredPhases=(refs.phases||[]).filter((x:any)=>!form.curriculumId||x.curriculumId===form.curriculumId);
 const filteredSubjects=(refs.subjects||[]).filter((x:any)=>x.isActive!==false);
 const filteredCP=(refs.outcomes||[]).filter((x:any)=>
   (!form.phaseId||x.phaseId===form.phaseId) &&
   (!form.curriculumId||x.curriculumId===form.curriculumId) &&
   (!form.subjectId||x.masterSubjectId===form.subjectId)
 );
 const filteredTP=(refs.objectives||[]).filter((x:any)=>!form.outcomeId||x.outcomeId===form.outcomeId);
 const filteredATP=(refs.sequences||[]).filter((x:any)=>!form.objectiveId||x.objectiveId===form.objectiveId);
 const filteredMaterials=(refs.materials||[]).filter((x:any)=>!form.sequenceId||x.sequenceId===form.sequenceId);
 const choose=(key:string,v:string)=>{
   const next:any={[key]:v};
   if(key==="curriculumId"){next.phaseId="";next.outcomeId="";next.objectiveId="";next.sequenceId="";next.materialId=""}
   if(key==="subjectId"){next.outcomeId="";next.objectiveId="";next.sequenceId="";next.materialId=""}
   if(key==="phaseId"){next.subjectId="";next.outcomeId="";next.objectiveId="";next.sequenceId="";next.materialId=""}
   if(key==="outcomeId"){next.objectiveId="";next.sequenceId="";next.materialId=""}
   if(key==="objectiveId"){next.sequenceId="";next.materialId=""}
   if(key==="sequenceId"){next.materialId=""}
   if(key==="subjectId"){const subject=(refs.subjects||[]).find((x:any)=>x.id===v); if(subject) next.subjectName=subject.name}
   if(key==="phaseId"){const phase=(refs.phases||[]).find((x:any)=>x.id===v); if(phase) next.content={...(form.content||{}),fase:phase.name};}
   setForm((f:any)=>({...f,...next}));
 };
 const set=(k:string,v:any)=>setForm((f:any)=>({...f,[k]:v}));const setContent=(k:string,v:string)=>setForm((f:any)=>({...f,content:{...(f.content||{}),[k]:v}}));
 async function save(){setSaving(true);setMessage("");try{const r=await fetch("/api/perangkat",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...form,type})});const d=await r.json();setMessage(r.ok?"Modul berhasil disimpan sebagai draft.":d.error||"Gagal menyimpan.");}catch{setMessage("Tidak dapat terhubung ke server.")}finally{setSaving(false)}}
 const dropdown=(label:string,key:string,list:any[])=> <label>{label}<select value={form[key]||""} onChange={e=>set(key,e.target.value)}><option value="">Pilih {label}</option>{list.map(x=><option key={x.id} value={x.id}>{x.name||x.title||x.content?.slice(0,70)}</option>)}</label>;
 return <main className="paShell"><header className="paTop"><div><Link href="/" className="back"><ArrowLeft size={16}/> Kembali ke Beranda</Link><p className="eyebrow">PERANGKAT AJAR</p><h1>Buat Perangkat Ajar</h1><p className="muted">Bangun perangkat berdasarkan Kurikulum Sekolah yang telah diaktifkan Admin Sekolah.</p></div><div className="paBadge"><BookOpen size={18}/> Guru • Matematika</div></header>
 <div className="typeGrid">{types.map(([v,l])=><button className={type===v?"type active":"type"} onClick={()=>setType(v)} key={v}><FileText size={16}/>{l}</button>)}</div>
 <section className="paCard"><h2>Identitas Perangkat</h2><div className="formGrid"><label>Judul Perangkat<input value={form.title} onChange={e=>set("title",e.target.value)} placeholder="Contoh: Modul Ajar Persamaan Kuadrat"/></label><label>Mata Pelajaran<input value={form.subjectName} onChange={e=>set("subjectName",e.target.value)} placeholder="Matematika"/></label><label>Kelas<input value={form.className} onChange={e=>set("className",e.target.value)} placeholder="IX"/></label><label>Tahun Ajaran<input value={form.academicYear} onChange={e=>set("academicYear",e.target.value)}/></label></div></section>
 <section className="paCard"><div className="paHead"><div><h2>Referensi Master Kurikulum</h2><p className="muted">Pilih CP, TP, ATP, dan Materi yang menjadi dasar perangkat.</p></div><span className="masterPill">KURIKULUM SEKOLAH • CP MASTER ⭐</span></div><div className="formGrid">
 <label>Kurikulum<select value={form.curriculumId||""} onChange={e=>choose("curriculumId",e.target.value)}><option value="">Pilih Kurikulum</option>{(refs.curricula||[]).map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label>Fase<select value={form.phaseId||""} disabled={!form.curriculumId} onChange={e=>choose("phaseId",e.target.value)}><option value="">{form.curriculumId?"Pilih Fase":"Pilih Kurikulum dahulu"}</option>{filteredPhases.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>\n <label>Mata Pelajaran<select value={form.subjectId||""} disabled={!form.phaseId} onChange={e=>choose("subjectId",e.target.value)}><option value="">{form.phaseId?"Pilih Mata Pelajaran":"Pilih Fase dahulu"}</option>{filteredSubjects.map((x:any)=><option key={x.id} value={x.id}>{x.name}</option>)}</select></label>
 <label>CP Master<select value={form.outcomeId||""} disabled={!form.subjectId} onChange={e=>choose("outcomeId",e.target.value)}><option value="">{form.subjectId?"Pilih CP":"Pilih Mata Pelajaran dahulu"}</option>{filteredCP.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>
 <label>TP<select value={form.objectiveId||""} disabled={!form.outcomeId} onChange={e=>choose("objectiveId",e.target.value)}><option value="">{form.outcomeId?"Pilih TP":"Pilih CP dahulu"}</option>{filteredTP.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>
 <label>ATP<select value={form.sequenceId||""} disabled={!form.objectiveId} onChange={e=>choose("sequenceId",e.target.value)}><option value="">{form.objectiveId?"Pilih ATP":"Pilih TP dahulu"}</option>{filteredATP.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>
 <label>Materi<select value={form.materialId||""} disabled={!form.sequenceId} onChange={e=>choose("materialId",e.target.value)}><option value="">{form.sequenceId?"Pilih Materi":"Pilih ATP dahulu"}</option>{filteredMaterials.map((x:any)=><option key={x.id} value={x.id}>{x.title}</option>)}</select></label>
 </div><div className="chain"><span><Target/> CP</span><ChevronRight/><span><Route/> TP</span><ChevronRight/><span><Route/> ATP</span><ChevronRight/><span><Layers/> Materi</span></div></section>
 {type==="MODUL_AJAR"&&<section className="paCard"><div className="paHead"><div><h2>Struktur Modul Ajar</h2><p className="muted">Isi bagian-bagian modul sesuai kebutuhan pembelajaran.</p></div></div><div className="moduleGrid">{moduleFields.map(([key,label,help])=><label key={key}>{label}<small>{help}</small><textarea value={form.content?.[key]||""} onChange={e=>setContent(key,e.target.value)}/></label>)}</div></section>}
{type==="LKPD"&&<section className="paCard"><div className="paHead"><div><h2>Struktur LKPD</h2><p className="muted">Lembar kerja peserta didik yang siap dikembangkan menjadi dokumen.</p></div></div><div className="moduleGrid">{[["tujuan","Tujuan Pembelajaran","Tujuan yang hendak dicapai melalui LKPD."],["petunjuk","Petunjuk Pengerjaan","Petunjuk kerja individu/kelompok."],["stimulus","Stimulus / Materi","Teks, kasus, gambar, data, atau situasi pemantik."],["kegiatan","Aktivitas Peserta Didik","Langkah kegiatan dan tugas yang dikerjakan."],["pertanyaan","Pertanyaan / Tugas","Pertanyaan pemahaman, penerapan, atau analisis."],["produk","Produk / Hasil Kerja","Hasil yang harus dikumpulkan peserta didik."],["rubrik","Rubrik Penilaian","Kriteria dan skala penilaian hasil kerja."],["refleksi","Refleksi Peserta Didik","Pertanyaan refleksi setelah kegiatan."]].map(([key,label,help])=><label key={key}>{label}<small>{help}</small><textarea value={form.content?.[key]||""} onChange={e=>setContent(key,e.target.value)}/></label>)}</div></section>}
{type==="ASESMEN"&&<section className="paCard"><div className="paHead"><div><h2>Struktur Asesmen</h2><p className="muted">Susun instrumen asesmen berdasarkan tujuan pembelajaran.</p></div></div><div className="moduleGrid">{[["tujuan","Tujuan Asesmen","Kompetensi yang akan diukur."],["diagnostik","Asesmen Diagnostik","Instrumen untuk mengetahui kesiapan awal."],["formatif","Asesmen Formatif","Instrumen pemantauan proses belajar."],["sumatif","Asesmen Sumatif","Instrumen penilaian pencapaian akhir."],["kisiKisi","Kisi-Kisi / Indikator","Indikator, materi, level kognitif, dan bentuk soal."],["instrumen","Instrumen / Soal","Soal atau tugas yang akan diberikan."],["kunci","Kunci Jawaban","Jawaban atau pedoman penyelesaian."],["rubrik","Rubrik / Pedoman Skor","Kriteria dan pembobotan penilaian."],["tindakLanjut","Tindak Lanjut","Remedial, pengayaan, atau tindak lanjut hasil asesmen."]].map(([key,label,help])=><label key={key}>{label}<small>{help}</small><textarea value={form.content?.[key]||""} onChange={e=>setContent(key,e.target.value)}/></label>)}</div></section>}
 <section className="paCard"><h2>{type==="MODUL_AJAR"?"Catatan Tambahan":"Isi / Catatan"}</h2><textarea className="contentArea" value={form.content?.catatan||""} onChange={e=>setContent("catatan",e.target.value)} placeholder="Catatan tambahan..."/><div className="paActions"><button className="save" disabled={saving} onClick={save}><Save size={16}/>{saving?"Menyimpan...":"Simpan Draft"}</button>{message&&<span className="message">{message}</span>}</div></section>
 </main>
}