"use client";
import {useEffect,useState} from "react";
import Link from "next/link";
import {LayoutDashboard,Users,School,BookOpen,ClipboardList,Settings,ChevronRight,Clock,LogOut} from "lucide-react";
import "./school-admin.css";

export default function SchoolAdminPage(){
 const [d,setD]=useState<any>(null);
 useEffect(()=>{fetch("/api/school-admin/dashboard").then(r=>r.json()).then(setD)},[]);
 if(!d)return <main className="saShell"><p>Memuat dashboard sekolah...</p></main>;
 const s=d.school;
 return <main className="saShell"><aside className="saSide"><div className="saBrand"><div className="saLogo">G</div><div><b>GuruWali</b><span>Admin Sekolah</span></div></div><div className="saSchool"><School size={18}/><div><b>{s?.name||"Sekolah"}</b><span>{s?.npsn?"NPSN "+s.npsn:"NPSN belum diisi"}</span></div></div><nav><Link className="saNav active" href="/school-admin"><LayoutDashboard/><span>Dashboard</span></Link><Link className="saNav" href="/school-admin/guru"><Users/><span>Guru</span></Link><Link className="saNav" href="/admin/sekolah/permintaan"><Clock/><span>Permintaan Guru</span>{d.pending>0&&<em>{d.pending}</em>}</Link><Link className="saNav" href="/school-admin/kelas"><School/><span>Kelas</span></Link><Link className="saNav" href="/school-admin/kurikulum"><BookOpen/><span>Kurikulum Sekolah</span></Link><Link className="saNav" href="/school-admin/dapodik"><BookOpen/><span>Import Dapodik</span></Link><Link className="saNav" href="/school-admin/perangkat"><ClipboardList/><span>Perangkat Guru</span></Link><Link className="saNav" href="/school-admin/pengaturan"><Settings/><span>Pengaturan</span></Link></nav><div className="saBottom"><button><LogOut size={17}/> Keluar</button></div></aside><section className="saContent"><header><p className="eyebrow">ADMIN SEKOLAH</p><h1>Dashboard {s?.name||"Sekolah"}</h1><p className="muted">Kelola guru, kelas, kurikulum, dan perangkat pembelajaran sekolah.</p></header><div className="saStats"><div><Users/><span>Guru Aktif</span><b>{d.guru}</b></div><div><School/><span>Kelas</span><b>{d.kelas}</b></div><div><ClipboardList/><span>Perangkat Guru</span><b>{d.devices}</b></div><div className={d.pending?"pending":""}><Clock/><span>Permintaan</span><b>{d.pending}</b></div></div><div className="saGrid"><div className="saCard"><h2>Akses Cepat</h2><Link href="/school-admin/guru"><Users/><div><b>Daftar Guru</b><span>Lihat guru yang aktif di sekolah</span></div><ChevronRight/></Link><Link href="/admin/sekolah/permintaan"><Clock/><div><b>Permintaan Bergabung</b><span>{d.pending} permintaan menunggu</span></div><ChevronRight/></Link><Link href="/school-admin/perangkat"><ClipboardList/><div><b>Perangkat Guru</b><span>Perangkat yang dibuat untuk sekolah</span></div><ChevronRight/></Link><Link href="/school-admin/dapodik"><BookOpen/><div><b>Import Profil Dapodik</b><span>Isi identitas sekolah dari file Profil Dapodik</span></div><ChevronRight/></Link></div><div className="saCard"><h2>Profil Sekolah</h2><p><b>{s?.name}</b></p><p>{s?.address||"Alamat belum diisi"}</p><p>{s?.principalName?"Kepala Sekolah: "+s.principalName:"Data kepala sekolah belum diisi"}</p></div></div></section></main>
}