"use client";
import {useState,useEffect} from "react";
import Link from "next/link";
import {BookOpen,ChevronRight,Plus,Star,Layers,Target,Route,ArrowLeft} from "lucide-react";
const tabs=["Kurikulum","Fase","Mata Pelajaran","CP Master","TP","ATP"];
export default function MasterPage(){
 const [tab,setTab]=useState("CP Master"); const [items,setItems]=useState<any[]>([]); const [loading,setLoading]=useState(false); const [form,setForm]=useState<any>({}); const [editing,setEditing]=useState<any>(null); const [saving,setSaving]=useState(false);
 const endpoints:any={"CP Master":"/api/master-kurikulum/outcomes","TP":"/api/master-kurikulum/objectives","ATP":"/api/master-kurikulum/sequences","Mata Pelajaran":"/api/master-kurikulum/subjects","Fase":"/api/master-kurikulum/phases","Kurikulum":"/api/master-kurikulum/curricula"};
 useEffect(()=>{setLoading(true);fetch(endpoints[tab]).then(r=>r.ok?r.json():[]).then(setItems).catch(()=>setItems([])).finally(()=>setLoading(false))},[tab]);
 async function reload(){const res=await fetch(endpoints[tab]);setItems(res.ok?await res.json():[])}
 async function save(){setSaving(true);try{const base=endpoints[tab];let url=base;let method="POST";if(editing){url=base+"/"+editing.id;method="PATCH"};const res=await fetch(url,{method,headers:{"Content-Type":"application/json"},body:JSON.stringify(form)});if(!res.ok){const e=await res.json();alert(e.error||"Gagal menyimpan");return}setForm({});setEditing(null);await reload()}finally{setSaving(false)}}
 function startAdd(){setEditing(null);setForm({});}
 function startEdit(x:any){setEditing(x);setForm({name:x.name||"",code:x.code||"",description:x.description||"",curriculumId:x.curriculumId||"",phaseId:x.phaseId||"",masterSubjectId:x.masterSubjectId||"",outcomeId:x.outcomeId||x.outcome?.id||"",objectiveId:x.objectiveId||x.objective?.id||"",title:x.title||"",content:x.content||""})}
 const fields=tab==="CP Master"?["title","content"]:tab==="TP"?["title","content"]:tab==="ATP"?["title","content"]:tab==="Mata Pelajaran"?["name","code"]:tab==="Fase"?["name","curriculumId"]:["name","description"];
 return <main className="mkShell"><header className="mkTop"><div><Link href="/admin" className="back"><ArrowLeft size={16}/> Dashboard Admin</Link><p className="eyebrow">MASTER KURIKULUM</p><h1>Master Kurikulum GuruWali</h1><p className="muted">Kelola data resmi platform yang menjadi sumber perangkat pembelajaran sekolah.</p></div><button className="mkPrimary" onClick={startAdd}><Plus size={17}/> Tambah Data</button></header><div className="mkNotice"><Star size={18} fill="currentColor"/><div><b>Data Master Platform ⭐</b><span>Admin GuruWali dapat memperbarui data. Sekolah dan guru menggunakan data ini sebagai referensi resmi.</span></div></div><div className="mkTabs">{tabs.map(t=><button key={t} onClick={()=>setTab(t)} className={tab===t?"selected":""}>{t}</button>)}</div><section className="mkToolbar"><div><h2>{tab}</h2><p className="muted">{loading?"Memuat data...":items.length+" data tersedia"}</p></div><div className="mkCount">{tab==="CP Master"?"⭐ Master Platform":tab}</div></section><div className="mkList">{items.map((x:any,i)=><article className="dataCard" key={x.id}><div className="dataIcon">{tab==="CP Master"?<Star size={17}/>:tab==="TP"?<Target size={17}/>:tab==="ATP"?<Route size={17}/>:<Layers size={17}/>}</div><div className="dataBody"><div className="dataTitle"><b>{x.name||x.title}</b>{tab==="CP Master"&&<span className="masterTag"><Star size={12} fill="currentColor"/> MASTER</span>}</div><span>{x.code||x.phase?.name||x.outcome?.title||x.objective?.title||x.description||"Data Master GuruWali"}</span><p>{x.content||""}</p></div><button className="editBtn">Edit</button></article>)}{!loading&&!items.length&&<div className="emptyMaster"><Layers size={34}/><h3>Belum ada data</h3><p>Tambahkan data {tab} untuk membangun Master Kurikulum.</p><button className="mkPrimary"><Plus size={16}/> Tambah {tab}</button></div>}</div>{<div className="editorPanel"><div className="editorHead"><div><b>{editing?"Edit":"Tambah"} {tab}</b><span>Data akan disimpan ke PostgreSQL melalui API GuruWali.</span></div><button onClick={()=>{setEditing(null);setForm({})}}>Tutup</button></div><div className="formGrid">{fields.map((f:string)=><label key={f}>{f==="title"?"Judul":f==="content"?"Isi":f==="name"?"Nama":f==="code"?"Kode":f==="description"?"Deskripsi":f==="curriculumId"?"Kurikulum":f==="phaseId"?"Fase":f==="masterSubjectId"?"Mata Pelajaran Master":f==="outcomeId"?"CP":f==="objectiveId"?"TP":f}<textarea className={f==="content"||f==="description"?"large":""} value={form[f]||""} onChange={e=>setForm({...form,[f]:e.target.value})}/></label>)}</div><button className="mkPrimary" disabled={saving} onClick={save}>{saving?"Menyimpan...":"Simpan"}</button></div>}</main>}